global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'websocket-server'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: 'load-test'
    static_configs:
      - targets: ['host.docker.internal:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
